name: Production deployment from master

on: 
  push:
    branches:
      - master

env:
  DBT_PROFILE_TARGET:            prod
  DBT_PROFILE_SCHEMA:            STAGING
  DBT_PROFILE_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_PROFILE_SNOWFLAKE_ACCOUNT }}
  DBT_PROFILE_USER:              ${{ secrets.DBT_PROFILE_USER }}
  DBT_PROFILE_PASSWORD:          ${{ secrets.DBT_PROFILE_PASSWORD }}
  DBT_PROFILE_ROLE:              TRANSFORMER
  DBT_PROFILE_DB:                JAFFLE_SHOP
  DBT_PROFILE_WH:                TRANSFORMING  

jobs:
  prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Install Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install DBT
      run: |
        python -m pip install --upgrade pip
        pip install dbt

    - name: Deploy
      run: |
        dbt run --profiles-dir ./ci_profiles
        dbt test --profiles-dir ./ci_profiles
    